server:
  addr: ":8080"
  loglevel: "info"

profiles:
  du4lcombined:
    source: "http://api:3000/calendar.ics"
    public: true
    modules:
    - name: "add-url"
      url: "https://outlook.live.com/owa/calendar/00000000-0000-0000-0000-000000000000/d8c3ea1e-74f4-4920-8b55-6166e4c9f57e/cid-DB8463EC38A495B6/calendar.ics"
