[server]
addr = ":8080"
loglevel = "debug"

[profiles]
  [profiles.du4lcombined]
    url = "http://api:3000/calendar.ics"
    regex = [""]
    public = true
    from = "1970-01-01T00:00:00Z"
    until = "1970-01-01T01:00:00Z"
    passid = true
    addurl = ["https://your.external-calendar.org/owa/calendar.ics"]
